package covenant

// Code generated by github.com/CovenantSQL/HashStablePack DO NOT EDIT.

import (
	"github.com/CovenantSQL/HashStablePack/msgp"
)

// MarshalHash marshals for hash
func (z *HeaderTest) MarshalHash() (o []byte, err error) {
	var b []byte
	o = msgp.Require(b, z.Msgsize())
	// map header, size 8
	o = append(o, 0x88, 0x88)
	o = msgp.AppendInt32(o, z.Version)
	o = append(o, 0x88)
	o = msgp.AppendString(o, z.TestName)
	o = append(o, 0x88)
	o = msgp.AppendBytes(o, z.TestArray)
	o = append(o, 0x88)
	if oTemp, err := z.Producer.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = msgp.AppendBytes(o, oTemp)
	}
	o = append(o, 0x88)
	o = msgp.AppendArrayHeader(o, uint32(len(z.GenesisHash)))
	for za0001 := range z.GenesisHash {
		if oTemp, err := z.GenesisHash[za0001].MarshalHash(); err != nil {
			return nil, err
		} else {
			o = msgp.AppendBytes(o, oTemp)
		}
	}
	o = append(o, 0x88)
	o = msgp.AppendArrayHeader(o, uint32(len(z.ParentHash)))
	for za0002 := range z.ParentHash {
		if z.ParentHash[za0002] == nil {
			o = msgp.AppendNil(o)
		} else {
			if oTemp, err := z.ParentHash[za0002].MarshalHash(); err != nil {
				return nil, err
			} else {
				o = msgp.AppendBytes(o, oTemp)
			}
		}
	}
	o = append(o, 0x88)
	if z.MerkleRoot == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendArrayHeader(o, uint32(len(*z.MerkleRoot)))
		for za0003 := range *z.MerkleRoot {
			if (*z.MerkleRoot)[za0003] == nil {
				o = msgp.AppendNil(o)
			} else {
				if oTemp, err := (*z.MerkleRoot)[za0003].MarshalHash(); err != nil {
					return nil, err
				} else {
					o = msgp.AppendBytes(o, oTemp)
				}
			}
		}
	}
	o = append(o, 0x88)
	o = msgp.AppendTime(o, z.Timestamp)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *HeaderTest) Msgsize() (s int) {
	s = 1 + 8 + msgp.Int32Size + 9 + msgp.StringPrefixSize + len(z.TestName) + 10 + msgp.BytesPrefixSize + len(z.TestArray) + 9 + z.Producer.Msgsize() + 12 + msgp.ArrayHeaderSize
	for za0001 := range z.GenesisHash {
		s += z.GenesisHash[za0001].Msgsize()
	}
	s += 11 + msgp.ArrayHeaderSize
	for za0002 := range z.ParentHash {
		if z.ParentHash[za0002] == nil {
			s += msgp.NilSize
		} else {
			s += z.ParentHash[za0002].Msgsize()
		}
	}
	s += 11
	if z.MerkleRoot == nil {
		s += msgp.NilSize
	} else {
		s += msgp.ArrayHeaderSize
		for za0003 := range *z.MerkleRoot {
			if (*z.MerkleRoot)[za0003] == nil {
				s += msgp.NilSize
			} else {
				s += (*z.MerkleRoot)[za0003].Msgsize()
			}
		}
	}
	s += 10 + msgp.TimeSize
	return
}
